name: 每日早报定时推送
on:
  workflow_dispatch:
  schedule:
    - cron: "18 14 * * *" # 每天早上8点推送
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 安装python环境
        uses: actions/setup-python@v3
        
      - name: 安装依赖
        run: |
           pip install requests
        
      - name: 开始推送
        env:
          wpush_apikey: ${{WPUSHXpKXYXzgaQ0rcrDcR94YC8p77JK}} # wpush apikey
          alapi_token: ${{Lh8PzTMgnuzsbfjj}}
          type: ${{ secrets.TYPE }}
          channel: ${{ secrets.CHANNEL }}
        run: |
          python 60s.py
